apiVersion: v1
kind: Service
metadata:
  name: {{ include "veleroApp.fullname" . }}
  labels:
    {{- include "veleroApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.veleroApp.service.type }}
  ports:
    - port: {{ .Values.veleroApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "veleroApp.selectorLabels" . | nindent 4 }}

