apiVersion: v1
kind: Service
metadata:
  name: {{ include "veleroApi.fullname" . }}
  labels:
    {{- include "veleroApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.veleroApi.service.type }}
  ports:
    - port: {{ .Values.veleroApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "veleroApi.selectorLabels" . | nindent 4 }}

