{{- if .Values.ubireport.ingress.enabled -}}
{{- $fullName := include "ubireport.fullnameOverride" . -}}
{{- $svcPort := .Values.ubireport.service.port -}}
apiVersion: networking.k8s.io/v1
#apiVersion: networking.k8s.io/v1beta1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ubireport.labels" . | nindent 4 }}
  {{- with .Values.ubireport.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ubireport.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ubireport.ingress.className }}
  {{- end }}
  {{- if .Values.ubireport.ingress.tls }}
  tls:
    {{- range .Values.ubireport.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ubireport.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
