apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veleroApi.fullname" . }}-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ .Values.veleroApi.secret.spring_datasource_url }}
  SERVER_PORT: {{ .Values.veleroApi.secret.server_port }}
  SERVER_SERVLET_CONTEXT-PATH: {{ .Values.veleroApi.secret.server_servlet_context_path }}
  SPRING_CLOUD_VAULT_K8S_CONFIGPATH: {{ .Values.veleroApi.secret.spring_cloud_vault_k8s_configpath }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.veleroApi.secret.spring_datasource_username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.veleroApi.secret.spring_datasource_password }}
  SPRING_CLOUD_VAULT_HOST: {{ .Values.veleroApi.secret.spring_cloud_vault_host }}
  SPRING_CLOUD_VAULT_PORT: {{ .Values.veleroApi.secret.spring_cloud_vault_port }}
  SPRING_CLOUD_VAULT_TOKEN: {{ .Values.veleroApi.secret.spring_cloud_vault_token }}
  SPRING_CLOUD_VAULT_K8S_PROJECTID: {{ .Values.veleroApi.secret.spring_cloud_vault_k8s_projectid }}
